In [1]:
#**Practica 1-Introducción a Python y a los sistemas discretos**

In [3]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

In [5]:

# Se crea un par de vectores a y b
a = np.array([3.1, 1, -0.5, -3.2, 6])
b = np.array([1, 3, 2.2, 5.1, 1])

In [8]:
# Se realiza la multiplicación escalar de a y b con el método  
# dot().
c = a.dot(b)
print("a•b =", c)

a•b = -5.32


In [9]:
# Se implementa la multiplicación punto a punto de a y b.
c = a*b
print("a*b =", c)


a*b = [  3.1    3.    -1.1  -16.32   6.  ]


In [10]:
# Se crea una matriz A 3x3.
A = np.array([[2, -1, -3], [4, 1.5, -2.5], [7.3, -0.9, 0.2]])


In [11]:
# Se obtiene la matriz transpuesta de A.
AT = np.transpose(A)
print("A^T =\n", AT)

A^T =
 [[ 2.   4.   7.3]
 [-1.   1.5 -0.9]
 [-3.  -2.5  0.2]]


In [12]:
# Ejemplificando las funciones ones, round, ceil y floor.
#  - ones: Crea una matriz o vector de unos, 
#          enteros o flotantes.
unit_matrix = np.ones((3, 3), int)
print("Matriz de unos:\n", unit_matrix)

#  - round: Redondea los elementos de una matriz o vector a 
#           cierta cantidad de decimales.
example_matrix = np.array([[1.234, 2.345, 3.456], 
                           [4.567, 5.678, 6.789]])
rounded_matrix = np.round(example_matrix, 2)
print("Matriz redondeada a 2 decimales:\n", rounded_matrix)

# - ceil: Redondea los elementos de una matriz o vector al
#         entero superior más cercano.
ceiled_matrix = np.ceil(example_matrix)
print("Matriz redondeada al entero superior más cercano:\n", 
      ceiled_matrix)

# - floor: Redondea los elementos de una matriz o vector al
#          entero inferior más cercano.
floored_matrix = np.floor(example_matrix)
print("Matriz redondeada al entero inferior más cercano:\n", 
      floored_matrix)

Matriz de unos:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Matriz redondeada a 2 decimales:
 [[1.23 2.35 3.46]
 [4.57 5.68 6.79]]
Matriz redondeada al entero superior más cercano:
 [[2. 3. 4.]
 [5. 6. 7.]]
Matriz redondeada al entero inferior más cercano:
 [[1. 2. 3.]
 [4. 5. 6.]]
